[package]
name = "speako_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
speako_core = { path = "../core" }
console_error_panic_hook = "0.1.7"
